### ISSUE TITLE
mvn exec:java for slotupgrader

### ISSUE THREAD

**Issue by confile** [ArcBees/gwtp-extensions#27]
The command above leads to: 

```
java.lang.ClassNotFoundException: com.arcbees.gwtp.upgrader.Upgrader
	at java.net.URLClassLoader$1.run(URLClassLoader.java:366)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:355)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(URLClassLoader.java:354)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:425)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:358)
	at org.codehaus.mojo.exec.ExecJavaMojo$1.run(ExecJavaMojo.java:281)
	at java.lang.Thread.run(Thread.java:745)
```

**Comment by meriouma** [comment]
You need to do `mvn package exec:java`, otherwise the classes aren't compiled. I'll update the README. Thanks!
